#!/bin/bash

# Script to create a directory named my_first_directory in the /tmp/ directory

directory_path="/tmp/my_first_directory"

mkdir "$directory_path"

# Verify the directory creation
file "$directory_path"


