#!/bin/bash

# Script to delete the directory my_first_directory from /tmp

directory_path="/tmp/my_first_directory"

# Delete the directory
rmdir "$directory_path"

# Verify the deletion
file "$directory_path"

